# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: G.U.I.D.E-CSharp - Godot Unified Input Detection Engine C#
email: na
author: Phlegmlee
description: >- # this means to ignore newlines until "baseurl:"
  A C# wrapped version of G.U.I.D.E, a simple but powerful way to handle input in the Godot Engine.

  This plugin is updated in tandem with the original plugin until such a time that a better alternative comes along.

baseurl: "/G.U.I.D.E-CSharp" # the subpath of your site, e.g. /blog

url: "https://Phlegmlee.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

show_downloads: true
github:
  zip_url: https://github.com/Phlegmlee/G.U.I.D.E-CSharp/archive/refs/heads/main.zip
  asset_lib_url: https://godotengine.org/asset-library/asset/5104

issue_tracker: "https://github.com/Phlegmlee/G.U.I.D.E-CSharp/issues"

repo: "https://github.com/Phlegmlee/G.U.I.D.E-CSharp"
github_username:  "Phlegmlee"
github_repo: "G.U.I.D.E-CSharp"
github_branch: "main"

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
